//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RSLibDemo.rc
//
#define IDD_RSLIBDEMO_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DLG_PREVIEW                 129
#define IDD_DLG_PLAYBACK                130
#define IDD_DLG_CONFIG                  131
#define IDD_DLG_PLAYER                  132
#define IDD_DLG_SEARCH                  133
#define IDB_BITMAP1                     134
#define IDB_BITMAP_LIST                 134
#define IDD_DLG_WINDOW                  135
#define IDD_DLG_INFO                    138
#define IDR_MENU_DEVICE_TREECTRL        139
#define IDD_DLG_UPGRADE1                141
#define IDR_MENU1                       145
#define IDR_MENU_STREAM_TYPE            145
#define IDD_DLG_WEB                     150
#define IDC_TREE_DEVICE                 1000
#define IDC_TAB_GLOBAL                  1007
#define IDC_LIST_DEVICE                 1010
#define IDC_EDIT_IP                     1011
#define IDC_EDIT_PORT                   1012
#define IDC_EDIT_NAME                   1013
#define IDC_EDIT_PASSWORD               1014
#define IDC_BTN_ADD                     1015
#define IDC_BTN_REFRESH                 1016
#define IDC_BTN_LU                      1016
#define IDC_BTN_U                       1017
#define IDC_BTN_SEARCH_DAY              1018
#define IDC_EDIT_WEB_PORT               1018
#define IDC_BTN_START                   1019
#define IDC_BTN_MODIFY                  1019
#define IDC_BTN_START_DOWNLOAD          1021
#define IDC_BTN_STOP_DOWNLOAD           1022
#define IDC_BTN_STOP                    1023
#define IDC_BTN_PAUSE                   1024
#define IDC_BTN_SLOW                    1027
#define IDC_BTN_FAST                    1028
#define IDC_BTN_SEEK                    1029
#define IDC_BTN_IRIS_I                  1030
#define IDC_COMBO_FISHEYE               1031
#define IDC_LIST_ALARM                  1032
#define IDC_STA_PREVIEW_WND             1033
#define IDC_BTN_CAPTURE                 1034
#define IDC_STATIC_WND                  1035
#define IDC_BTN_START_REC               1035
#define IDC_BTN_STOP_REC                1036
#define IDC_LIST_DOWNLOAD               1038
#define IDC_TIME_PICKER                 1039
#define IDC_STATIC_PLAYBACK_WND         1040
#define IDC_BTN_RU                      1041
#define IDC_BTN_L                       1042
#define IDC_BTN_A                       1043
#define IDC_BTN_R                       1044
#define IDC_BTN_LD                      1045
#define IDC_BTN_D                       1046
#define IDC_BTN_RD                      1047
#define IDC_BTN_ZOOM_D                  1048
#define IDC_BTN_ZOOM_I                  1049
#define IDC_BTN_FOCUS_D                 1050
#define IDC_BTN_FOCUS_I                 1051
#define IDC_BTN_IRIS_D                  1052
#define IDC_STATIC_INFO                 1053
#define IDC_MONTH_PICKER                1054
#define IDC_BTN_SEARCH_MONTH            1055
#define IDC_CHECK1                      1056
#define IDC_CHECK2                      1057
#define IDC_CHECK3                      1058
#define IDC_CHECK4                      1059
#define IDC_CHECK5                      1060
#define IDC_CHECK6                      1061
#define IDC_CHECK7                      1062
#define IDC_CHECK8                      1063
#define IDC_CHECK9                      1064
#define IDC_CHECK10                     1065
#define IDC_CHECK11                     1066
#define IDC_CHECK12                     1067
#define IDC_CHECK13                     1068
#define IDC_CHECK14                     1069
#define IDC_CHECK15                     1070
#define IDC_CHECK16                     1071
#define IDC_CHECK17                     1072
#define IDC_CHECK18                     1073
#define IDC_CHECK19                     1074
#define IDC_CHECK20                     1075
#define IDC_CHECK21                     1076
#define IDC_CHECK22                     1077
#define IDC_CHECK23                     1078
#define IDC_CHECK24                     1079
#define IDC_CHECK25                     1080
#define IDC_CHECK26                     1081
#define IDC_CHECK27                     1082
#define IDC_CHECK28                     1083
#define IDC_CHECK29                     1084
#define IDC_CHECK30                     1085
#define IDC_CHECK31                     1086
#define IDC_COMBO_RECORD_TYPE           1087
#define IDC_BTN_LIVE_CHANNEL            1088
#define IDC_BTNUPGRADE                  1089
#define IDC_BTN_OPEN_SOUND              1091
#define IDC_BTN_CLOSE_SOUND             1092
#define IDC_SLIDER_PLAYER               1093
#define IDC_STATIC_PLAYER_WND           1094
#define IDC_EDIT2                       1096
#define IDC_EDT_FILE                    1096
#define IDC_BTN_FILE                    1097
#define IDC_BTN_QUERY                   1098
#define IDC_BTN_SET                     1099
#define IDC_STATIC_CONFIG               1100
#define IDC_BUTTON1                     1101
#define IDC_BTN_OPEN                    1101
#define IDC_BTN_REVERSE_RECORD          1101
#define IDC_BTN_USER                    1101
#define IDC_COMBO_NET_MODE              1102
#define IDC_LIST1                       1103
#define IDC_COMBO2                      1105
#define IDC_COMBO_CAPTURE_TYPE          1105
#define IDC_BUTTON2                     1106
#define IDC_BTN_CAPTURE_FROM_DEVICE     1106
#define IDC_BTN_HDD                     1106
#define IDC_BTN_CAPTURE_TO_BUF          1107
#define IDC_BUTTON3                     1108
#define IDC_BTN_JSON                    1108
#define IDC_STATIC_DAY_SEARCH           1109
#define IDC_BTN_HUMAN_ALARM             1109
#define IDC_STATIC_PTZ                  1110
#define IDC_BTN_HUMAN_PARAM             1110
#define IDC_STATIC_FISHEYE              1111
#define IDC_STATIC_MONTH_SEARCH         1112
#define IDC_STATIC_PLAYBACK_CONTROL     1113
#define IDC_GROUP_RIGHT                 1114
#define IDC_GROUP_LEFT                  1115
#define IDC_EXPLORER1                   1120
#define IDC_EXPLORER_WEB                1120
#define ID_STOPPREVIEW                  32772
#define ID_STARTPREVIEW                 32773
#define ID_Menu                         32774
#define ID__STARTDUAL                   32775
#define ID__STOPTALK                    32776
#define ID__STARTTALK                   32777
#define ID_STOPTALK                     32778
#define ID_STARTTALK                    32779
#define ID_MAIN_STREAM                  32780
#define ID_SUBSTREAM                    32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
